<a href="https://colab.research.google.com/github/moridin04/CCMACLRL_EXAM_COM221ML/blob/main/Midterm_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [225]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.api as sm

from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

In [226]:
dataset_url = 'https://github.com/robitussin/CCMACLRL_EXAM/blob/a46a4e2a001dedaefc9b431d480b508ce86c2d96/datasets/train.csv?raw=true'
df = pd.read_csv(dataset_url)
df.head()

,id,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
0,0,MINI,Cooper S Base,2007,213000,Gasoline,172.0HP 1.6L 4 Cylinder Engine Gasoline Fuel,A/T,Yellow,Gray,None reported,Yes,4200
1,1,Lincoln,LS V8,2002,143250,Gasoline,252.0HP 3.9L 8 Cylinder Engine Gasoline Fuel,A/T,Silver,Beige,At least 1 accident or damage reported,Yes,4999
2,2,Chevrolet,Silverado 2500 LT,2002,136731,E85 Flex Fuel,320.0HP 5.3L 8 Cylinder Engine Flex Fuel Capab...,A/T,Blue,Gray,None reported,Yes,13900
3,3,Genesis,G90 5.0 Ultimate,2017,19500,Gasoline,420.0HP 5.0L 8 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,Black,Black,None reported,Yes,45000
4,4,Mercedes-Benz,Metris Base,2021,7388,Gasoline,208.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,7-Speed A/T,Black,Beige,None reported,Yes,97500

In [227]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 188533 entries, 0 to 188532
Data columns (total 13 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   id            188533 non-null  int64
 1   brand         188533 non-null  object
 2   model         188533 non-null  object
 3   model_year    188533 non-null  int64
 4   milage        188533 non-null  int64
 5   fuel_type     183450 non-null  object
 6   engine        188533 non-null  object
 7   transmission  188533 non-null  object
 8   ext_col       188533 non-null  object
 9   int_col       188533 non-null  object
 10  accident      186081 non-null  object
 11  clean_title   167114 non-null  object
 12  price         188533 non-null  int64
dtypes: int64(4), object(9)
memory usage: 18.7+ MB

In [228]:
df.isnull().sum()

id                  0
brand               0
model               0
model_year          0
milage              0
fuel_type        5083
engine              0
transmission        0
ext_col             0
int_col             0
accident         2452
clean_title     21419
price               0
dtype: int64

In [229]:
df.dropna(inplace=True)

In [230]:
df.isnull().sum()

id              0
brand           0
model           0
model_year      0
milage          0
fuel_type       0
engine          0
transmission    0
ext_col         0
int_col         0
accident        0
clean_title     0
price           0
dtype: int64

In [231]:
df.describe()

                  id     model_year         milage         price
count  162610.000000  162610.000000  162610.000000  1.626100e+05
mean    94197.039137    2015.158822   71105.487086  4.081699e+04
std     54467.770815       5.699531   50157.874111  7.653857e+04
min         0.000000    1974.000000     100.000000  2.000000e+03
25%     47026.250000    2012.000000   29000.000000  1.570000e+04
50%     94139.000000    2016.000000   64300.000000  2.850000e+04
75%    141421.750000    2019.000000  101000.000000  4.699900e+04
max    188532.000000    2024.000000  405000.000000  2.954083e+06

In [232]:
df.sample(20)

,id,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
109767,109767,MINI,Cooper Base,2009,90367,Gasoline,118.0HP 1.6L 4 Cylinder Engine Gasoline Fuel,6-Speed M/T,Red,Black,None reported,Yes,12000
60597,60597,Bentley,Continental GT W12,2017,51855,Gasoline,582.0HP 6.0L 12 Cylinder Engine Gasoline Fuel,A/T,Black,Black,None reported,Yes,14950
54330,54330,Lexus,LX 570 Three-Row,2023,5000,Gasoline,383.0HP 5.7L 8 Cylinder Engine Gasoline Fuel,A/T,Green,Black,None reported,Yes,94000
27092,27092,Mercedes-Benz,S-Class S 550 4MATIC,2018,27300,Gasoline,449.0HP 4.7L 8 Cylinder Engine Gasoline Fuel,9-Speed A/T,White,White,None reported,Yes,53500
104059,104059,Jeep,Grand Cherokee L Limited,2021,12875,Gasoline,3.6L V6 24V MPFI DOHC,8-Speed Automatic,Metallic,Global Black,None reported,Yes,43147
49244,49244,Ford,Utility Police Interceptor Base,2017,105667,E85 Flex Fuel,300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capa...,6-Speed A/T,White,Black,At least 1 accident or damage reported,Yes,35000
41409,41409,Ford,Mustang GT,2005,57912,Gasoline,300.0HP 4.6L 8 Cylinder Engine Gasoline Fuel,6-Speed A/T,Brown,Gray,None reported,Yes,25000
69613,69613,Porsche,911 Turbo,2021,223824,Gasoline,572.0HP 3.8L Flat 6 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,Black,Black,None reported,Yes,46900
159116,159116,Porsche,911 Carrera Cabriolet,2002,90000,Gasoline,300.0HP 3.4L Flat 6 Cylinder Engine Gasoline Fuel,6-Speed M/T,Black,Black,None reported,Yes,30900
15643,15643,Toyota,Supra A91-MT Edition,2023,15000,Hybrid,382.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,9-Speed A/T,Gray,Black,None reported,Yes,41000
1822,1822,Mercedes-Benz,S-Class S 560 4MATIC,2023,2046,Gasoline,463.0HP 4.0L 8 Cylinder Engine Gasoline Fuel,9-Speed A/T,Black,Black,None reported,Yes,95000
178117,178117,Chevrolet,Silverado 1500 LT Trail Boss,2021,52775,Gasoline,5.3L V8 16V GDI OHV,Automatic,White,Jet Black,None reported,Yes,32612
18976,18976,Dodge,Durango GT,2020,54000,Gasoline,325.0HP 2.7L V6 Cylinder Engine Gasoline Fuel,10-Speed A/T,Blue,Gray,None reported,Yes,37300
86499,86499,Jeep,Wrangler Sport,2016,136731,Gasoline,285.0HP 3.6L V6 Cylinder Engine Gasoline Fuel,A/T,Black,Black,None reported,Yes,15000
172331,172331,Ford,Shelby GT350 Base,2018,61802,Gasoline,526.0HP 5.2L 8 Cylinder Engine Gasoline Fuel,A/T,Black,Black,None reported,Yes,48000
148105,148105,Cadillac,Escalade ESV Sport,2022,47466,Gasoline,6.2L V8 16V GDI OHV,10-Speed Automatic,Silver,Shara Beige,None reported,Yes,38322
19302,19302,BMW,M760 i xDrive,2014,99897,Gasoline,601.0HP 6.6L 12 Cylinder Engine Gasoline Fuel,8-Speed A/T,White,Red,None reported,Yes,18000
85821,85821,Ford,F-150 XLT,2018,456,Gasoline,375.0HP 3.5L V6 Cylinder Engine Gasoline Fuel,10-Speed A/T,Gray,Gray,None reported,Yes,417500
187390,187390,Ford,F-150 XLT,2016,52675,E85 Flex Fuel,385.0HP 5.0L 8 Cylinder Engine Flex Fuel Capab...,6-Speed A/T,White,Black,None reported,Yes,20000
187002,187002,Mercedes-Benz,GL-Class GL 450,2012,65000,Gasoline,335.0HP 4.7L 8 Cylinder Engine Gasoline Fuel,7-Speed A/T,Gray,Black,None reported,Yes,46500

In [233]:
from datetime import datetime

current_year = datetime.now().year
df['model_year'] = current_year - df['model_year'].astype(int)
df.head()

,id,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
0,0,MINI,Cooper S Base,17,213000,Gasoline,172.0HP 1.6L 4 Cylinder Engine Gasoline Fuel,A/T,Yellow,Gray,None reported,Yes,4200
1,1,Lincoln,LS V8,22,143250,Gasoline,252.0HP 3.9L 8 Cylinder Engine Gasoline Fuel,A/T,Silver,Beige,At least 1 accident or damage reported,Yes,4999
2,2,Chevrolet,Silverado 2500 LT,22,136731,E85 Flex Fuel,320.0HP 5.3L 8 Cylinder Engine Flex Fuel Capab...,A/T,Blue,Gray,None reported,Yes,13900
3,3,Genesis,G90 5.0 Ultimate,7,19500,Gasoline,420.0HP 5.0L 8 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,Black,Black,None reported,Yes,45000
4,4,Mercedes-Benz,Metris Base,3,7388,Gasoline,208.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,7-Speed A/T,Black,Beige,None reported,Yes,97500

In [234]:
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
label_encoder = LabelEncoder()
df['brand'] = label_encoder.fit_transform(df['brand'])
df['model'] = label_encoder.fit_transform(df['model'])
df['fuel_type'] = label_encoder.fit_transform(df['fuel_type'])
df['engine'] = label_encoder.fit_transform(df['engine'])
df['transmission'] = label_encoder.fit_transform(df['transmission'])
df['ext_col'] = label_encoder.fit_transform(df['ext_col'])
df['int_col'] = label_encoder.fit_transform(df['int_col'])
df['accident'] = label_encoder.fit_transform(df['accident'])
df['clean_title'] = label_encoder.fit_transform(df['clean_title'])

In [235]:
df

,id,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
0,0,31,493,17,213000,2,110,38,306,71,1,0,4200
1,1,28,925,22,143250,2,358,38,257,10,0,0,4999
2,2,9,1567,22,136731,1,627,38,37,71,1,0,13900
3,3,16,755,7,19500,2,846,49,28,14,1,0,45000
4,4,36,1072,3,7388,2,252,23,28,10,1,0,97500
...,...,...,...,...,...,...,...,...,...,...,...,...,...
188527,188527,9,402,25,110000,2,604,38,298,71,1,0,14500
188528,188528,8,601,7,49000,2,849,49,298,10,1,0,27500
188529,188529,36,204,6,28600,2,757,31,298,14,0,0,30000
188530,188530,36,221,3,13650,2,904,23,298,14,1,0,86900
188532,188532,43,1023,8,59500,2,356,49,298,14,1,0,28995

In [236]:
y_scaled = df['price']
y_scaled

0          4200
1          4999
2         13900
3         45000
4         97500
          ...
188527    14500
188528    27500
188529    30000
188530    86900
188532    28995
Name: price, Length: 162610, dtype: int64

In [237]:
x = df.drop(['price'],axis=1)
x

,id,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title
0,0,31,493,17,213000,2,110,38,306,71,1,0
1,1,28,925,22,143250,2,358,38,257,10,0,0
2,2,9,1567,22,136731,1,627,38,37,71,1,0
3,3,16,755,7,19500,2,846,49,28,14,1,0
4,4,36,1072,3,7388,2,252,23,28,10,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
188527,188527,9,402,25,110000,2,604,38,298,71,1,0
188528,188528,8,601,7,49000,2,849,49,298,10,1,0
188529,188529,36,204,6,28600,2,757,31,298,14,0,0
188530,188530,36,221,3,13650,2,904,23,298,14,1,0
188532,188532,43,1023,8,59500,2,356,49,298,14,1,0

1. Use the Dataset file to train your model. Split this into train and test to calculate the RMSE

In [238]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(x, y_scaled, test_size=0.2, random_state=42)

In [239]:
model = LinearRegression()

In [240]:
model.fit(X_train, y_train)

LinearRegression()

In [241]:
y_pred = model.predict(X_test)

In [242]:
mean_squared_error(y_test, y_pred, squared=False)

79047.5545875024

In [243]:
test_url = 'https://github.com/robitussin/CCMACLRL_EXAM/blob/a46a4e2a001dedaefc9b431d480b508ce86c2d96/datasets/test.csv?raw=true'
dt = pd.read_csv(test_url)

In [244]:
sample_submission_url = 'https://github.com/robitussin/CCMACLRL_EXAM/blob/a46a4e2a001dedaefc9b431d480b508ce86c2d96/datasets/sample_submission.csv?raw=true'
sf = pd.read_csv(sample_submission_url)

In [245]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 162610 entries, 0 to 188532
Data columns (total 13 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   id            162610 non-null  int64
 1   brand         162610 non-null  int64
 2   model         162610 non-null  int64
 3   model_year    162610 non-null  int64
 4   milage        162610 non-null  int64
 5   fuel_type     162610 non-null  int64
 6   engine        162610 non-null  int64
 7   transmission  162610 non-null  int64
 8   ext_col       162610 non-null  int64
 9   int_col       162610 non-null  int64
 10  accident      162610 non-null  int64
 11  clean_title   162610 non-null  int64
 12  price         162610 non-null  int64
dtypes: int64(13)
memory usage: 17.4 MB

In [246]:
dt.info()
dt.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125690 entries, 0 to 125689
Data columns (total 12 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   id            125690 non-null  int64
 1   brand         125690 non-null  object
 2   model         125690 non-null  object
 3   model_year    125690 non-null  int64
 4   milage        125690 non-null  int64
 5   fuel_type     122307 non-null  object
 6   engine        125690 non-null  object
 7   transmission  125690 non-null  object
 8   ext_col       125690 non-null  object
 9   int_col       125690 non-null  object
 10  accident      124058 non-null  object
 11  clean_title   111451 non-null  object
dtypes: int64(3), object(9)
memory usage: 11.5+ MB

(125690, 12)

In [247]:
from datetime import datetime

current_year = datetime.now().year
dt['model_year'] = current_year - dt['model_year'].astype(int)
dt.head()

,id,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title
0,188533,Land,Rover LR2 Base,9,98000,Gasoline,240.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,6-Speed A/T,White,Beige,None reported,Yes
1,188534,Land,Rover Defender SE,4,9142,Hybrid,395.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,8-Speed A/T,Silver,Black,None reported,Yes
2,188535,Ford,Expedition Limited,2,28121,Gasoline,3.5L V6 24V PDI DOHC Twin Turbo,10-Speed Automatic,White,Ebony,None reported,NaN
3,188536,Audi,A6 2.0T Sport,8,61258,Gasoline,2.0 Liter TFSI,Automatic,Silician Yellow,Black,None reported,NaN
4,188537,Audi,A6 2.0T Premium Plus,6,59000,Gasoline,252.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,A/T,Gray,Black,None reported,Yes

In [248]:
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
label_encoder = LabelEncoder()
dt['brand'] = label_encoder.fit_transform(dt['brand'])
dt['model'] = label_encoder.fit_transform(dt['model'])
dt['fuel_type'] = label_encoder.fit_transform(dt['fuel_type'])
dt['engine'] = label_encoder.fit_transform(dt['engine'])
dt['transmission'] = label_encoder.fit_transform(dt['transmission'])
dt['ext_col'] = label_encoder.fit_transform(dt['ext_col'])
dt['int_col'] = label_encoder.fit_transform(dt['int_col'])
dt['accident'] = label_encoder.fit_transform(dt['accident'])
dt['clean_title'] = label_encoder.fit_transform(dt['clean_title'])

In [249]:
id = sf.pop('id')
y_pred = model.predict(dt)

# Create a submission DataFrame
submission_df = pd.DataFrame({
    'id': id,
    'price': y_pred
})

# Save the submission DataFrame to a CSV file
submission_df.to_csv('submission_file.csv', index=False)
print("Submission file created: submission_file.csv")

Submission file created: submission_file.csv